#!/usr/bin/env python3
"""Generate Rust test vectors from the RFC 8448 section 3 handshake trace.

The vectors in `tests/vectors/rfc8448_sec3.rs` are generated by this script
rather than transcribed, so they cannot drift from the published RFC through a
copy error. Regenerate with:

    curl -sO https://www.rfc-editor.org/rfc/rfc8448.txt
    python3 tools/gen_rfc8448_vectors.py rfc8448.txt \
        > tests/vectors/rfc8448_sec3.rs

Two independent checks make silent corruption unlikely: every field's byte
count is compared against the `(N octets)` figure the RFC prints beside it, and
every selected operation is matched against its expected party and operation
name, so any reflow of the source document fails loudly.
"""

import json
import re
import sys

SECTION_START = re.compile(r"^3\.\s+Simple 1-RTT Handshake\s*$")
SECTION_END = re.compile(r"^4\.\s+Resumed 0-RTT Handshake\s*$")

HEADER_RE = re.compile(r"^\s{3}\{(client|server)\}\s+(.*?):?\s*$")
FIELD_RE = re.compile(r"^\s{6}([a-zA-Z0-9 _\"'()./-]+?)\s*\((\d+)\s+octets\)\s*:\s*(.*)$")
NOISE_RE = re.compile(r"^(Thomson\s+Informational|RFC 8448\s+TLS 1\.3 Traces|\f)")
HEX_LINE_RE = re.compile(r"^[0-9a-f\s]+$")


def extract_section(lines):
    """Returns just the lines of section 3."""
    start = end = None
    for i, line in enumerate(lines):
        if start is None and SECTION_START.match(line.rstrip("\n")):
            start = i
        elif start is not None and SECTION_END.match(line.rstrip("\n")):
            end = i
            break
    if start is None or end is None:
        raise SystemExit("could not locate section 3 boundaries in the RFC text")
    return lines[start:end]


def parse(lines):
    """Parses `{party} operation:` blocks and their `name (N octets):` fields."""
    entries = []
    cur = None
    cur_field = None

    def flush_field():
        nonlocal cur_field
        if cur_field is None:
            return
        name, declared, parts = cur_field
        hexstr = "".join(parts).replace(" ", "")
        if hexstr == "(empty)":
            hexstr = ""
        try:
            data = bytes.fromhex(hexstr)
        except ValueError as exc:
            raise SystemExit(f"bad hex for {name!r} in {cur['op']!r}: {exc}") from exc
        if len(data) != declared:
            raise SystemExit(
                f"length mismatch for {name!r} in {cur['op']!r}: "
                f"RFC declares {declared} octets, parsed {len(data)}"
            )
        cur["fields"].append({"name": name, "hex": data.hex()})
        cur_field = None

    for raw in lines:
        line = raw.rstrip("\n")
        if NOISE_RE.match(line) or NOISE_RE.match(line.strip()) or not line.strip():
            continue

        m = HEADER_RE.match(line)
        if m:
            flush_field()
            if cur:
                entries.append(cur)
            cur = {"party": m.group(1), "op": m.group(2).strip(), "fields": []}
            continue

        m = FIELD_RE.match(line)
        if m and cur is not None:
            flush_field()
            cur_field = (m.group(1).strip(), int(m.group(2)), [m.group(3).strip() + " "])
            continue

        if cur_field is not None:
            stripped = line.strip()
            indent = len(line) - len(line.lstrip())
            if HEX_LINE_RE.match(stripped) and indent >= 6:
                cur_field[2].append(stripped + " ")
                continue
            flush_field()

    flush_field()
    if cur:
        entries.append(cur)
    return entries


# (index, party, operation prefix, kind, Rust constant name)
SELECTION = [
    (0, "client", "create an ephemeral x25519 key pair", "kx", "CLIENT_X25519"),
    (4, "server", "create an ephemeral x25519 key pair", "kx", "SERVER_X25519"),

    (3, "server", 'extract secret "early"', "extract0", "EARLY_EXTRACT"),
    (6, "server", 'derive secret for handshake "tls13 derived"', "derive", "DERIVED_FOR_HANDSHAKE"),
    (7, "server", 'extract secret "handshake"', "extract", "HANDSHAKE_EXTRACT"),
    (8, "server", 'derive secret "tls13 c hs traffic"', "derive", "C_HS_TRAFFIC"),
    (9, "server", 'derive secret "tls13 s hs traffic"', "derive", "S_HS_TRAFFIC"),
    (10, "server", 'derive secret for master "tls13 derived"', "derive", "DERIVED_FOR_MASTER"),
    (11, "server", 'extract secret "master"', "extract", "MASTER_EXTRACT"),

    (13, "server", "derive write traffic keys for handshake data", "keys", "SERVER_HS_KEYS"),
    (24, "server", "derive read traffic keys for handshake data", "keys", "CLIENT_HS_KEYS"),
    (23, "server", "derive write traffic keys for application data", "keys", "SERVER_AP_KEYS"),
    (42, "client", "derive write traffic keys for application data", "keys", "CLIENT_AP_KEYS"),

    (17, "server", 'calculate finished "tls13 finished"', "finished", "SERVER_FINISHED"),
    (39, "client", 'calculate finished "tls13 finished"', "finished", "CLIENT_FINISHED"),

    (20, "server", 'derive secret "tls13 c ap traffic"', "derive", "C_AP_TRAFFIC"),
    (21, "server", 'derive secret "tls13 s ap traffic"', "derive", "S_AP_TRAFFIC"),
    (22, "server", 'derive secret "tls13 exp master"', "derive", "EXP_MASTER"),
    (43, "client", 'derive secret "tls13 res master"', "derive", "RES_MASTER"),

    (1, "client", "construct a ClientHello handshake message", "msg", "CLIENT_HELLO"),
    (5, "server", "construct a ServerHello handshake message", "msg", "SERVER_HELLO"),
    (14, "server", "construct an EncryptedExtensions handshake message", "msg", "ENCRYPTED_EXTENSIONS"),
    (15, "server", "construct a Certificate handshake message", "msg", "CERTIFICATE"),
    (16, "server", "construct a CertificateVerify handshake message", "msg", "CERTIFICATE_VERIFY"),
    (18, "server", "construct a Finished handshake message", "msg", "SERVER_FINISHED_MSG"),
    (40, "client", "construct a Finished handshake message", "msg", "CLIENT_FINISHED_MSG"),

    (19, "server", "send handshake record", "record", "SERVER_FLIGHT_RECORD"),
    (41, "client", "send handshake record", "record", "CLIENT_FINISHED_RECORD"),
    (51, "client", "send application_data record", "record", "CLIENT_APPDATA_RECORD"),
    (52, "server", "send application_data record", "record", "SERVER_APPDATA_RECORD"),
    (53, "client", "send alert record", "record", "CLIENT_ALERT_RECORD"),
]

ALIASES = {
    "private key": "private_key",
    "public key": "public_key",
    "key info": "key_info",
    "key expanded": "key",
    "iv info": "iv_info",
    "iv expanded": "iv",
    "complete record": "complete",
    "expanded": "out",
    "secret": "out",
    "finished": "verify_data",
    "IKM": "ikm",
    "PRK": "prk",
}

KIND_FIELDS = {
    "kx": ("Kx", ["private_key", "public_key"]),
    "extract0": ("Extract", ["ikm", "out"]),
    "extract": ("Extract", ["salt", "ikm", "out"]),
    "derive": ("Derive", ["prk", "hash", "info", "out"]),
    "keys": ("TrafficKeys", ["prk", "key_info", "key", "iv_info", "iv"]),
    "finished": ("FinishedVec", ["prk", "hash", "info", "out", "verify_data"]),
    "record": ("Record", ["payload", "complete"]),
}

PREAMBLE = '''// RFC 8448 section 3, "Simple 1-RTT Handshake", as test vectors.
//
// GENERATED FILE — do not edit. Produced by `tools/gen_rfc8448_vectors.py`
// from the RFC 8448 plain-text source. Every value was checked against the
// `(N octets)` length the RFC prints beside it at generation time.
//
// The handshake is X25519 + `TLS_AES_128_GCM_SHA256`, server-authenticated,
// no PSK — exactly the narrow profile the MPC backend targets.
//
// This file is `include!`d into a module, so it carries no inner attributes;
// the including module applies `#[allow(dead_code)]`.

/// An `HKDF-Extract` step.
pub struct Extract {
    pub salt: &'static [u8],
    pub ikm: &'static [u8],
    pub out: &'static [u8],
}

/// A `Derive-Secret` step, including the serialized `HkdfLabel` (`info`) so
/// label construction is verified independently of the output.
pub struct Derive {
    pub prk: &'static [u8],
    pub hash: &'static [u8],
    pub info: &'static [u8],
    pub out: &'static [u8],
}

/// Traffic key material derived from one traffic secret.
pub struct TrafficKeys {
    pub prk: &'static [u8],
    pub key_info: &'static [u8],
    pub key: &'static [u8],
    pub iv_info: &'static [u8],
    pub iv: &'static [u8],
}

/// A `finished_key` derivation and the resulting `verify_data`.
pub struct FinishedVec {
    pub prk: &'static [u8],
    pub hash: &'static [u8],
    pub info: &'static [u8],
    pub out: &'static [u8],
    pub verify_data: &'static [u8],
}

/// A record. `payload` is the content *before* the content-type byte is
/// appended; `complete` is the wire record including its 5-byte header.
pub struct Record {
    pub payload: &'static [u8],
    pub complete: &'static [u8],
}

/// An ephemeral X25519 key pair.
pub struct Kx {
    pub private_key: &'static [u8],
    pub public_key: &'static [u8],
}
'''


def hexlit(h):
    b = bytes.fromhex(h)
    if not b:
        return "&[]"
    lines = [
        "        " + " ".join(f"0x{x:02x}," for x in b[i : i + 12])
        for i in range(0, len(b), 12)
    ]
    return "&[\n" + "\n".join(lines) + "\n    ]"


def main():
    with open(sys.argv[1]) as f:
        entries = parse(extract_section(f.readlines()))

    out = [PREAMBLE]
    for idx, party, op_prefix, kind, name in SELECTION:
        if idx >= len(entries):
            raise SystemExit(f"index {idx} out of range ({len(entries)} operations parsed)")
        e = entries[idx]
        if e["party"] != party or not e["op"].startswith(op_prefix):
            raise SystemExit(
                f"selection mismatch at index {idx}: expected {{{party}}} "
                f"{op_prefix!r}, found {{{e['party']}}} {e['op']!r}"
            )

        fields = {ALIASES.get(f["name"], f["name"]): f["hex"] for f in e["fields"]}
        out.append(f"/// `{{{party}}} {e['op']}`")

        if kind == "msg":
            if len(e["fields"]) != 1:
                raise SystemExit(f"{name}: expected exactly one field")
            out.append(f"pub const {name}: &[u8] = {hexlit(e['fields'][0]['hex'])};\n")
            continue

        struct, want = KIND_FIELDS[kind]
        if kind == "extract0":
            # The early extract uses an all-zero salt; the RFC omits the field.
            fields["salt"] = "00" * 32
            want = ["salt", "ikm", "out"]

        missing = [k for k in want if k not in fields]
        if missing:
            raise SystemExit(f"{name}: missing fields {missing}; have {sorted(fields)}")

        out.append(f"pub const {name}: {struct} = {struct} {{")
        for k in want:
            out.append(f"    {k}: {hexlit(fields[k])},")
        out.append("};\n")

    sys.stdout.write("\n".join(out))
    print(f"generated {len(SELECTION)} vectors from {len(entries)} operations", file=sys.stderr)


if __name__ == "__main__":
    main()
